# Generated by Django 4.2.3 on 2023-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('datehiked', models.DateField()),
                ('elevation', models.IntegerField()),
            ],
        ),
    ]
